### PR TITLE
Update API Key, URL

### PR DESCRIPTION
**Pull request by seanlane**
Update the repo to use a user specific API key from Mashape or a client id from Domainr. The key or id is stored in a config .ini file within the Domainr package, and is imported with the package when running the installation. Also add a small change to a print statement for Python 3 compatibility.

### CODE REVIEW

**Comment by seanlane** [comment]
for @zachwill I updated the README so it would make sense when looking at it from my repo, since it may be some time until this pull request is approved.

**Comment by strycore** [comment]
@zachwill it's ok if you don't have time to work on the project anymore but be considerate and give push access to @seanlane since he's willing to maintain the project.

**Comment by seanlane** [comment]
@strycore and for anyone else, for what it's worth, my fork can be found here: https://github.com/seanlane/dom

**Comment by zachwill** [comment]
Adding on @seanlane as a maintainer 👍

**Pull request merged**
